# Generated by Django 5.2.8 on 2025-12-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_description', models.TextField(max_length=2000)),
                ('room_no', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_dimension', models.CharField(max_length=50)),
                ('room_bed_no', models.CharField(max_length=50)),
                ('room_occupants_no', models.CharField(max_length=100)),
                ('room_meal_access', models.CharField(max_length=100)),
                ('room_electricity', models.BooleanField(default=True)),
                ('room_AC', models.BooleanField(default=True)),
                ('room_pool_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_number', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotelApp.hotelroomsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotelApp.hotelroomsmodel')),
            ],
        ),
    ]
