# Generated by Django 5.2.8 on 2025-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomsmodel',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
