# Generated by Django 5.2.8 on 2025-12-08 00:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='room_name'),
        ),
    ]
