# Generated by Django 5.2.8 on 2025-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelusers',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
