# Generated by Django 5.2.8 on 2026-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_alter_hotelusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsmodel',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
