# Generated by Django 5.2.8 on 2025-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_hotelroomsmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out',
        ),
    ]
