# Generated by Django 5.2.8 on 2025-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_hotelroomsmodel_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsmodel',
            name='room_description',
            field=models.TextField(max_length=2000),
        ),
    ]
