# Generated by Django 5.2.8 on 2025-12-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_rename_end_date_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(max_length=50),
        ),
    ]
