# Generated by Django 5.2.8 on 2026-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_alter_hotelroomsmodel_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsmodel',
            name='room_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
