# Generated by Django 5.2.8 on 2026-01-07 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0004_alter_hotelroomsmodel_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsmodel',
            name='room_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
