# Generated by Django 5.2.8 on 2025-12-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0004_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_number',
            new_name='guest_phone',
        ),
    ]
