# Generated by Django 5.2.8 on 2025-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0005_rename_guest_number_booking_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_refrence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed')], default='pending', max_length=40, null=True),
        ),
    ]
