# Generated by Django 5.2.8 on 2025-12-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0006_booking_created_at_booking_payment_refrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
